[package]

name = "tkr-app"
version = "0.1.0"
authors = ["Michael Guerrier <token.thinkers@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[profile.dev.package.esp-wifi]
opt-level = 3


##########################################################
#               Core Project Dependencies                #
##########################################################
[dependencies]

log = "*"

embedded-svc = { version = "*", default-features = false, features = [] }
embedded-io = "*"
embedded-io-async = "*"

embassy-time = { version = "*", features = ["nightly"] }
embassy-macros = "*"
embassy-futures = "*"
embassy-executor = { version = "^0.3.3", features = ["nightly"] }
embassy-sync = "*"
embassy-net = "*"

picoserve = "*"


smoltcp = { version = "*", default-features = false, features = [
    "socket-udp",
    "proto-igmp",
    "proto-ipv4",
    "socket-raw",
    "socket-tcp",
    "socket-icmp",
    "proto-dhcpv4",
    "socket-dhcpv4",
    "medium-ethernet",
] }
static_cell = { version = "*", features = ["nightly"] }


serde = { version = "*", default-features = false, features = ["derive"] }
serde_json = { version = "*", features = ["alloc"], default-features = false }


##########################################################
#              RP2040-Specific Dependencies              #
##########################################################
[target.thumbv6m-none-eabi.dependencies]

embassy-rp = "*"

##########################################################
#              ESP32-Specific Dependencies               #
##########################################################
[target.xtensa-esp32-none-elf.dependencies]

esp-println = { version = "*", features = ["log", "esp32"] }
esp-alloc = { version = "*" }

hal = { package = "esp32-hal", version = "*", features = [
    "log",
    "async",
    "embassy",
    "vectored",
    "embassy-time-timg0",
    "embassy-executor-thread",
    "embassy-executor-interrupt",
] }
esp-wifi = { version = "*", features = [
    "wifi",
    "async",
    "esp32",
    "utils",
    "esp-now",
    "wifi-logs",
    "embassy-net",
] }
esp-backtrace = { version = "*", features = [
    "esp32",
    "print-uart",
    "panic-handler",
    "exception-handler",
] }
