# Comments
format_code_in_doc_comments = true
normalize_comments          = true
wrap_comments               = true

# Imports
reorder_imports     = true
imports_indent      = "Block"
group_imports       = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout      = "HorizontalVertical"


# Enums
enum_discrim_align_threshold = 35


#Body
brace_style = "AlwaysNextLine"
control_brace_style = "ClosingNextLine"
condense_wildcard_suffixes = true
fn_params_layout = "Vertical"
fn_single_line = true