[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"


[env]
ESP_LOGLEVEL="INFO"


[build]
target = "xtensa-esp32-none-elf"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-Trom_functions.x",

  "-C", "link-arg=-nostartfiles",
]


[unstable]
build-std = ["alloc", "core"]

